apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example
  namespace: baltistan-dev
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
