kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: Test
  namespace: baltistan-dev
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: Test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: example
