apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mycontainer
      image: nginx
      securityContext:
        runAsUser: 1000
        capabilities:
          add: ["NET_ADMIN"]
